
Master:
  dialect: sqlite3
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: casbin
  charset: utf8
  showSql: true
  logLevel: debug
  maxOpenConns: 100 # 最大打开连接数
  maxIdleConns: 10 # 连接池的空闲数大小
Slave:
  dialect: sqlite3
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: casbin
  charset: utf8
  showSql: true
  logLevel: debug
  maxOpenConns: 100 # 最大打开连接数
  maxIdleConns: 10 # 连接池的空闲数大小
